### ISSUE TITLE
Tratamento de erros não está padronizado na rota POST /clientes

### ISSUE THREAD

**Issue by BrunoBorelliPro** [victorbern/ecommerce_celulou#3]
# Problema
Quando chamamos a rota POST /clientes com dados faltantes o que se espera é:
![image](https://github.com/user-attachments/assets/31ae6060-039e-4fc9-b2cf-517fc8c9db9b)
O que de fato ocorre na maioria das rotas.

Entretanto, quando mandamos um requisição sem o campo "celularCliente" recebemos a seguinte mensagem de erro: 
![image](https://github.com/user-attachments/assets/2404168f-7497-42cd-a165-a51d0cb681d7)
Mensagem que provem de um erro não tratado de forma correta lançado pela validação do Zod:
![image](https://github.com/user-attachments/assets/53b00dff-31b9-4d2d-ad8e-943939e00d88)
Dessa forma o usuário da API não será capaz de saber qual campo ficou faltando apenas lendo a mensagem de erro.

# Sugestão de resolução
O Zod lança uma mensagem de erro completa por padrão então talvez, se possível, utiliza-lo como classe de DTO possa ser uma boa escolha:
![image](https://github.com/user-attachments/assets/6b64676c-a1b2-4962-aa92-c0f4b35874b9)
![image](https://github.com/user-attachments/assets/d74e570a-9182-4819-af29-601848955241)

Repare que ele mostra exatamente onde o problema de validação está e qual é o problema de validação. Facilitando para o programador que usa a API a resolver o problema rapidamente.

**Comment by victorbern** [comment]
Agradeço por me alertar para este problema. Vi aqui e na verdade era um erro na validação do zod, eu estava validando caso celularCliente viesse vazio "", mas não para caso eu não recebesse nenhum celularCliente (recebesse um undefined).
![image](https://github.com/user-attachments/assets/8e52ae2e-6787-4f87-aedc-5ff58cdf9139)
